# Generated by Django 3.2.8 on 2021-10-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('cotacao', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
