# Generated by Django 3.2.8 on 2021-10-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
